export { default as loginApi } from './login'
export { default as userApi } from './user'
export { default as songApi } from './song'
export { default as searchApi } from './search'
export { default as bannerApi } from './banner'
export { default as recommendApi } from './recommend'
export { default as playlistApi } from './playlist'
export { default as artistApi } from './artist'
export { default as captchaApi } from './captcha'
// export { default as albumApi } from './album'
